---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: policyfile_zero
  require_chef_omnibus: 12.3.0
  data_bags_path: ../housepub-chef-repo/data_bags

platforms:
  - name: fedora-21

suites:
  - name: basement-server
